### ISSUE TITLE
More contents to this mod

### ISSUE THREAD

**Issue by dennisjosh16** [staticvoidliam7/MindustryPlusPlus#2]
I have an idea to add more additional contents to the mod like new units, turrets, resources and more! Maybe add a new planet so that it's not focused on the campaign.

**Comment by staticvoidliam7** [comment]
ok! this isn't actually my main project right now, but feel free to make suggestions

**Comment by dennisjosh16** [comment]
-add some new floors like new type of grass or rocks maybe add some plants and liquid resources too, if there will be a campaign.
-it will be cool if you added a few kinds of items that fuels a specific building or can be use as a ammo from the missile array or a turret.
-maybe add 2 or 3 types of unit like ground, air , and naval units.
Ground- shoots faster and causes more damage but less hp and armor
Air- it can be a bomber or full on ground and air support
Naval- that shoots very far but fires very slow
-add bosses for the planets like the "Martian Conqueror" (example only) from Mars
-Turrets
*Groundbreaker
Fires a large beam that can burn and deals a lot of damage.
*Galactum
Fires a small beams but has a very fast fire rate.
*Voldium
Good for air units. Shoots homing laser and explodes on impact.
*Cosmonus
Shoots a powerful orb that can deal huge damage on buildings and group enemies.

**Comment by staticvoidliam7** [comment]
Thanks for the ideas! I am restarting the project so I will definitely try to implement these!
